version: "3.8"

services:
  db:
    image: postgres:13.3-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/PGDATA
    ports:
      - 5432:5432
